num_epochs: 1000
val_interval: 50
batch_size: 16
num_workers: 4
pin_memory: true
device: cuda
save_only_one_checkpoint: true
num_images_to_log: 10

model:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: vgg16_bn
  encoder_weights: imagenet
  in_channels: 3
  activation:
    _target_: src.utils.misc.get_class
    obj:
      _target_: torch.nn.ReLU
  classes: 1

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0003

scheduler: null

train_transform:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Normalize
      max_pixel_value: 1.

val_transform:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Normalize
      max_pixel_value: 1.
