num_epochs: 3000
val_interval: 100
batch_size: 64
num_workers: 8
pin_memory: true
device: cuda
save_only_one_checkpoint: true
num_images_to_log: 10

model:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: vgg16_bn
  encoder_weights: imagenet
  in_channels: 3
  activation:
    _target_: src.utils.misc.get_class
    obj:
      _target_: torch.nn.ReLU
  classes: 1

loss:
  _target_: src.utils.composite_loss.CompositeLoss
  losses:
    - _target_: torch.nn.MSELoss
    - _target_: torchgeometry.losses.SSIM
      window_size: 5
      reduction: mean
  weights: [0.9, 0.1]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0003
  weight_decay: 0.05

scheduler: null

train_transform:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Normalize
      max_pixel_value: 1.
    - _target_: albumentations.Flip
      p: 0.75
    - _target_: albumentations.RandomRotate90
      p: 0.5
    - _target_: albumentations.ShiftScaleRotate
      shift_limit: 0.2
      scale_limit: 0.
      rotate_limit: 0
      p: 0.9

val_transform:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Normalize
      max_pixel_value: 1.
